apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-test-demo
spec:
  selector:
    matchLabels:
      app: k8-test-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: k8-test-demo
    spec:
      containers:
        - name: k8-test-demo
          image: k8-test-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      
        